### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by matdave** [saschiwy/script.start.moonlight-qt#1]
How is yours set up? I have moonlight-qt installed on raspbian, and when I click on this program in Kodi nothing happens. This simple wrapper seems like a perfect solution, but not sure what I'm missing.

**Comment by saschiwy** [comment]
Hey Mister,

you are absolutely right. I started to work on this plugin and then stepped back to libreelec. I never finished it. However, I created a fresh installation of raspbian and made the plugin working. Just tested it and it works like expected. 

Can you please follow the steps from the readme of the current commit in master branch and let me know if everything worked for you?

**Comment by saschiwy** [comment]
Closed due to inactivity
